### ISSUE TITLE
Todo before v1.0.0

### ISSUE THREAD

**Issue by IlanCosman** [IlanCosman/tide#1]
- [x] Generalize left side of prompt
- [x] Improve color variable names
- [x] Improve README with images, explanations etc.
- [x] Refactor configuration wizard
