### ISSUE TITLE
Todo v1.1.0

### ISSUE THREAD

**Issue by IlanCosman** [IlanCosman/tide#3]
- [x] Make pwd smarter
- [x] Have wizard restore default config (icons, colors etc.)
- [x] Add completions for tide command
- [x] Get a vanity git.io link
