### ISSUE TITLE
Todo 2.0.0

### ISSUE THREAD

**Issue by IlanCosman** [IlanCosman/tide#4]
- [x] Bump version number
- [x] Powerline
  - [x] Separators
    - [x] Same Color
    - [x] Different Color
  - [x] Frame
    - [x] Left
    - [x] Right
  - [x] Configuration Wizard menus
- [x] Documentation
  - [x] Get a banner/logo
  - [x] Use a left right alternation for images/text
  - [x] Use wiki for configuration
  - [x] Update for powerline
